Importing libraries and Datasets

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Uploading the Dataset
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
#Renaming the colomns name for Modern Data
df = df.rename(columns={'Age':'Age','Fare':'Cost_USD','Pclass':'Service_Tier'})

In [4]:
#(rows,Columns)
df.shape

(891, 12)

In [5]:
#display the first 10 rows
df.head(10)

,PassengerId,Survived,Service_Tier,Name,Sex,Age,SibSp,Parch,Ticket,Cost_USD,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [6]:
#missing values in the Each columns
df.isna().sum()

PassengerId       0
Survived          0
Service_Tier      0
Name              0
Sex               0
Age             177
SibSp             0
Parch             0
Ticket            0
Cost_USD          0
Cabin           687
Embarked          2
dtype: int64

In [7]:
#Calculating the threshold value
total_rows = 891
missing_threshold = total_rows * 0.70
print(f'Maximum missing values allowed: {missing_threshold}')

Maximum missing values allowed: 623.6999999999999

In [8]:
#dropping the colomn Cabin it has too many missing values
df.drop(columns=['Cabin'], inplace=True)

In [9]:
#Finding the medain value of Age
median_Age = np.nanmedian(df['Age'])
print(f'Median Age : {median_Age}')

Median Age : 28.0

In [10]:
#Filling the nan values 
df['Age'] = df['Age'].fillna(median_Age)
df

,PassengerId,Survived,Service_Tier,Name,Sex,Age,SibSp,Parch,Ticket,Cost_USD,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [11]:
#Giving the value with the Unknown
df['Embarked'] = df['Embarked'].fillna('Unknown')

In [12]:
#Exact rows with NaN in Embarked has been changed to Unknown
df.loc[[61,829]]

,PassengerId,Survived,Service_Tier,Name,Sex,Age,SibSp,Parch,Ticket,Cost_USD,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,Unknown
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,Unknown

In [13]:
#Checking Again to Conform No Null values
df.isna().sum()

PassengerId     0
Survived        0
Service_Tier    0
Name            0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Cost_USD        0
Embarked        0
dtype: int64

In [14]:
#New Column Created for Cost in INR
df['Cost_INR'] = df['Cost_USD'] * 83.5
df

,PassengerId,Survived,Service_Tier,Name,Sex,Age,SibSp,Parch,Ticket,Cost_USD,Embarked,Cost_INR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,605.37500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,5952.15555
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,661.73750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,4433.85000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,672.17500
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,1085.50000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,2505.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,1958.07500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,2505.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,647.12500

In [15]:


# Corrected parenthetical nesting
df['Age_Group'] = np.where(
    df['Age'] < 18, 
    'Minor', 
    np.where((df['Age'] >= 18) & (df['Age'] < 60), 'Adult', 'Senior')
)
df

,PassengerId,Survived,Service_Tier,Name,Sex,Age,SibSp,Parch,Ticket,Cost_USD,Embarked,Cost_INR,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,605.37500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,5952.15555,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,661.73750,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,4433.85000,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,672.17500,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,1085.50000,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,2505.00000,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,1958.07500,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,2505.00000,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,647.12500,Adult

In [16]:
#Age Category
df['Age_Group'].value_counts()

Age_Group
Adult     752
Minor     113
Senior     26
Name: count, dtype: int64

In [17]:
#Cost_usd and Age ,sum and mean value
df.groupby('Service_Tier')[['Cost_USD','Age']].agg(['sum','mean'])

                Cost_USD                  Age
                     sum       mean       sum       mean
Service_Tier
1             18177.4125  84.154687   7951.42  36.812130
2              3801.8417  20.662183   5476.83  29.765380
3              6714.6951  13.675550  12732.92  25.932627

In [18]:
#Amount spend by each age group
df.groupby('Age_Group')['Cost_USD'].max()

Age_Group
Adult     512.3292
Minor     211.3375
Senior    263.0000
Name: Cost_USD, dtype: float64